### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by santacrab2** [santacrab2/3DS-PokeAutoBot#1]
3ds link trade bot updates (in priority order)
- [x] finish remote control tab with touchscreen, (maybe joystick?!)
- [x] add settings for discord announcements bot name, role to ping when turning on, message, toggle announcements on and off.
- [x] read wondertrade trade partners info if possible and log/display
- [x] add Whos that pokemon mode
- [x] Remote Control Tab
- [x] Read GTS requests and apply receivers trainer info
- [x] have bot only cancel trades sent to it instead of constantly spamming X
- [x] add a catch for when it gives you the person has been added at the start of a friend code add
- [x] Offsets for all gen 7 versions
- [x] clean bad friend code user input strings
- [x] block z-crystals they do not trade.
- [x] make wiki for bot hosts
- [x] remove chat services tab and make everything operate under connect button
- [x] add a screen refresh for initial entry into fest plaza
- [x] gen 7 GTS bot
- [x] gen 7 WT bot
- [x] dumping
- [x] reading pk7 file info
- [x] queue clear command for users
- [x] queue empty for owner
- [x] settings tab
- [x] bad fc add recovery
- [x] second in-festival plaza value needs to be added
- [x] bad WT recovery for gen 7
- [x] catch for when user exits trade before the bot
